# Generated by Django 6.0.1 on 2026-03-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
