# Generated by Django 6.0.1 on 2026-03-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(default='S,M,L,XL', max_length=100),
        ),
    ]
