# Generated by Django 6.0.3 on 2026-03-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_cart_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
